---
image: docker:stable
services:
 - docker:dind
stages:
 - linting
 - build_and_push
 - build_hub
variables:
  DOCKER_DRIVER: overlay2
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"
  LATEST_TAG: latest
  UBUNTU_CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE
  HUB_RELEASE_IMAGE: docker.io/saltman33/ansible-ubuntu-bionic
  ANSIBLE_LIBRARY: $ANSIBLE_LIBRARY
  ANSIBLE_VERBOSITY: $ANSIBLE_VERBOSITY
  ANSIBLE_ROLES_PATH: $ANSIBLE_ROLES_PATH
  ANSIBLE_HOST_KEY_CHECKING: $ANSIBLE_HOST_KEY_CHECKING
  ANSIBLE_LOG_PATH: $ANSIBLE_LOG_PATH
  ANSIBLE_EXECUTABLE: $ANSIBLE_EXECUTABLE
  ANSIBLE_BECOME: $ANSIBLE_BECOME
  ANSIBLE_BECOME_USER: $ANSIBLE_BECOME_USER
  ANSIBLE_PIPELINING: $ANSIBLE_PIPELINING
  ANSIBLE_INVENTORY: $ANSIBLE_INVENTORY
  ANSIBLE_INVENTORY_ENABLED: $ANSIBLE_INVENTORY_ENABLED
  TTY: xterm
cache:
  paths:
    - .cache/
    - venv/
.linting: &linting
   stage: linting
dockerfile_lint:
   <<: *linting
   image: hadolint/hadolint:latest-debian
   script:
      - hadolint --config .hadolint.yaml ./Dockerfile
build_docker_gitlab:
  stage: build_and_push
  before_script:
      - "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY"
  script:
    - docker build --pull -t $UBUNTU_CONTAINER_RELEASE_IMAGE .
    - docker push $UBUNTU_CONTAINER_RELEASE_IMAGE:$LATEST_TAG
build_docker_hub:
  stage: build_hub
  before_script:
      - "docker login -u $HUB_USER -p $HUB_PW"
  script:
    - docker build --pull -t $HUB_RELEASE_IMAGE .
    - docker push $HUB_RELEASE_IMAGE:$LATEST_TAG
