---
image: docker:stable
services:
 - docker:dind
stages:
 - linting
 - build_and_push
 - build_hub
variables:
  DOCKER_DRIVER: overlay2
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"
  CONTAINER_IMAGE: registry.gitlab.com/$CI_PROJECT_PATH
  HUB_RELEASE_IMAGE: docker.io/saltman33/ansible-ubuntu-disco
cache:
  paths:
    - .cache/
    - venv/
.linting: &linting
   stage: linting
dockerfile_lint:
   <<: *linting
   image: hadolint/hadolint:latest-debian
   script:
      - hadolint --config .hadolint.yaml ./Dockerfile
build_docker_gitlab:
  stage: build_and_push
  before_script:
      - "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY"
  script:
    - docker pull $CONTAINER_IMAGE:latest
    - docker build --cache-from $CONTAINER_IMAGE:latest -t $CONTAINER_IMAGE:$CI_COMMIT_SHA -t $CONTAINER_IMAGE:$CI_BUILD_REF -t $CONTAINER_IMAGE:latest .
    - docker push $CONTAINER_IMAGE:$CI_BUILD_REF
    - docker push $CONTAINER_IMAGE:latest
    - docker push $CONTAINER_IMAGE:$CI_COMMIT_SHA
build_docker_hub:
  stage: build_hub
  before_script:
      - "docker login -u $HUB_USER -p $HUB_PW"
  script:
    - docker pull $HUB_RELEASE_IMAGE
    - docker build --cache-from $HUB_RELEASE_IMAGE:latest -t $HUB_RELEASE_IMAGE:$CI_COMMIT_SHA -t $HUB_RELEASE_IMAGE:$CI_BUILD_REF -t $HUB_RELEASE_IMAGE:latest .
    - docker push $HUB_RELEASE_IMAGE:$CI_BUILD_REF
    - docker push $HUB_RELEASE_IMAGE:latest
    - docker push $HUB_RELEASE_IMAGE:$CI_COMMIT_SHA
