---
image: docker:stable
services:
 - docker:dind
stages:
 - linting
 - build_and_push
 - build_hub
variables:
  DOCKER_DRIVER: overlay2
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"
  LATEST_TAG: latest
  BIONIC_TAG: bionic
  DISCO_TAG: disco
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest
  HUB_TEST_IMAGE: docker.io/saltman33/ansible-ubuntu-disco
  HUB_RELEASE_IMAGE: docker.io/saltman33/ansible-ubuntu
cache:
  paths:
    - .cache/
    - venv/
.linting: &linting
   stage: linting
dockerfile_lint:
   <<: *linting
   image: hadolint/hadolint:latest-debian
   script:
      - hadolint --config .hadolint.yaml ./Dockerfile
build_docker_gitlab:
  stage: build_and_push
  before_script:
      - "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY"
  script:
    - docker pull $CONTAINER_RELEASE_IMAGE
    - docker build --cache-from $CONTAINER_RELEASE_IMAGE --build-arg VER=$BIONIC_TAG -t $CONTAINER_RELEASE_IMAGE:$BIONIC_TAG --build-arg VER=$DISCO_TAG -t $CONTAINER_RELEASE_IMAGE:$DISCO_TAG -t $CONTAINER_RELEASE_IMAGE:$LATEST_TAG .
    - docker push $CONTAINER_RELEASE_IMAGE:$BIONIC_TAG
    - docker push $CONTAINER_RELEASE_IMAGE:$LATEST_TAG
    - docker push $CONTAINER_RELEASE_IMAGE:$DISCO_TAG
build_docker_hub:
  stage: build_hub
  before_script:
      - "docker login -u $HUB_USER -p $HUB_PW"
  script:
    - docker pull $HUB_TEST_IMAGE
    - docker build --cache-from $HUB_RELEASE_IMAGE --build-arg VER=$BIONIC_TAG -t $HUB_RELEASE_IMAGE:$BIONIC_TAG --build-arg VER=$DISCO_TAG -t $HUB_RELEASE_IMAGE:$DISCO_TAG -t $HUB_RELEASE_IMAGE:$LATEST_TAG .
    - docker push $HUB_RELEASE_IMAGE:$BIONIC_TAG
    - docker push $HUB_RELEASE_IMAGE:$LATEST_TAG
    - docker push $HUB_RELEASE_IMAGE:$DISCO_TAG
